### PR TITLE
delete.js was named with lowercase d, but reffered to as uppercase D …

### PR DESCRIPTION
**Pull request by StahlErik**
…from index.js. This caused problems on case-sensitive OS's

### CODE REVIEW

**Comment by StahlErik** [comment]
Unsure if renaming of file only was changed locally or if it is also part of push...

**Comment by codebyjonas** [comment]
> Unsure if renaming of file only was changed locally or if it is also part of push...

Should this be merged? I cant see file name change here on github

**Comment by codebyjonas** [comment]
Did these directly in dev.

**Comment by StahlErik** [comment]
issue #103 solved

**Pull request closed without merging**
